### ISSUE TITLE
Build script being interpreted as bash by default on macOS

### ISSUE THREAD

**Issue by ctrpetersen** [mrbrianevans/do-functions#1]
Hi - when running `do-functions`, the js build file was being interpreted as bash and failed to run. Adding a node shebang line (`#!/usr/bin/env node`) to the top of `.bin/do-functions.js` makes it correctly run with the nodejs runtime.

**Comment by tim-wise** [comment]
Was also happening to me, but I use fish.  @ctrpetersen 's fix worked.

**Comment by mrbrianevans** [comment]
Thank you, I have added this fix. Please try the latest version `v1.2.0`:
```
npm i do-functions@latest
```

Let me know if you experience any other issues or have suggestions for making this more useful.

**Comment by mrbrianevans** [comment]
Closing this issue as a fix has been published. Please re-open if you are still experiencing the problem with the latest version.
